---
title: "R Markdown Primer"
author: "Erico Cardelli Author"
output: html_document
---
# My First Section

We start a new section with a single HASHTAG and this is the first paragraph in that section.  Notice how the text wraps around to the next line in the editor but it still has the same line number and that's pretty cool.  That's because all text on a single line is considered a paragraph.

Leaving a blank line starts a new paragraph.  Remember Markdown is highly spaced and cased aware.
If you don't leave a blank line you are still in the same paragraph

So it is very important to pay attention to spaces.

F7 for spell check.

# New Section

You start a new section by leaving a blank line and then starting the next line with a hash tag.  No need to close the previous section, just start a new one. (Similar to La-Tex)

# Subsections

Creating a subsection is easy.  Two Hash tags

## This is a Subsection

We start a section in a section to start it

You can use add decorator module

## Another Subsection

Same rules apply no need to close previous subsection just keep a blank line in between them

the output type is actually an R function you are specifying and is in the R Markdown Package

# Back to Sections

# Formatting Text

One Underline is for _Emphasized_ 

_Emphasized Words Go Here_

Strong Text is with two underlines __Strong__

__Strong Text Goes Here__

And you can combine them with Three Underlines ___Bold and Strong___

And finally code snippets are the BACKTIC under the Esc

`This is computer Code`

# Lists

## Unordered List

Fruit

- Apple
- Orange
- Banana
- Mango
- Durian
- Watermellon
- Dragonfruit

## Ordered List

To createa an ordered list use 1. at the beginning of your list items
Hit Dice
and a sublist with a. to make the sublist

### Sublists

I added subs in there too

1. Bug
    a. gnat
    a. fly
    a. spider
    a. wasp
1. Fool
    i. dope
    i. idiot
1. Knight
1. Troll
1. Dragon

# Links

You put the text you want displayed in square brackets and then the url into parenthesis

`[Google](https://www.google.com)` = [Google](https://www.google.com)
